### ISSUE TITLE
Unit and integration test for WarningPanel Ui

### ISSUE THREAD

**Issue by flxffy** [CS2103-AY1819S2-T12-3/main#125]
- [x] Test that any arbitrary medicine is rendered properly in Warning Card.

- [x] Test that any arbitrary list of low stock medicine provided is rendered correctly in view.

- [x] Test that any arbitrary list of expiring medicine and batches provided is rendered correctly in view.

- [x] Test that any arbitrary list of medicine provided from Model is rendered correctly in view.

**Comment by JonathanLeeWH** [comment]
Make changes with permission from @flxffy
