### ISSUE TITLE
Unit test Warning Command in Logic

### ISSUE THREAD

**Issue by flxffy** [CS2103-AY1819S2-T12-3/main#127]
- [x] Test that arguments are parsed correctly.

- [x] Test that thresholds are set correctly.

- [x] Test that command results give right output.

**Comment by flxffy** [comment]
`WarningCommandParserTest#parse_allFieldsPresent_success` issue with tokenizer.

**Comment by JonathanLeeWH** [comment]
Move to milestone v1.4 with permission from @flxffy
