### ISSUE TITLE
As a pharmacist, I need to export the inventory data

### ISSUE THREAD

**Issue by flxffy** [CS2103-AY1819S2-T12-3/main#17]
so that I can easily send the compiled or required data to superiors/employers (in this case possibly the doctor or owner of the clinic) to notify them of the current medicine inventory status or to get approval to order new stocks. It also allows data to be easily compiled and send to medicine suppliers to allow them to know how much stocks my company is ordering or what existing stocks of our company are running low.

**Comment by JonathanLeeWH** [comment]
The export feature has been implemented and finalised of milestone v1.4
