### ISSUE TITLE
Sample MediTabs.json which we will include in v1.4 release

### ISSUE THREAD

**Issue by JonathanLeeWH** [CS2103-AY1819S2-T12-3/main#194]
@jtankw3 @flxffy @melpulomas 

This is the sample data of the `data.zip` which I created based on real medicine names. There are around 20 medicine names with appropriate tags like whether they are tablets, cream, etc.

I randomly created some batch numbers but the expiry dates might need some edits as we need to allow testers to see that medicines that are low in stock, expiring soon or have expired or properly shown.

The reason I created an issue in the issue tracker rather than submitting a PR as it will take a lot of time if everyone wants to edit this file and also Travis would have to keep checking each time you make a PR.

You can just update the `MediTabs.json` file in the `data.zip`'s `data` folder and attach your new `data.zip` file in your comment on this issue with what changes you made. We should finalised this as soon as possible as we will be including this `data.zip` file in the `v1.4` release together with `meditabs.jar`

The data.zip file is shown below
[data.zip](https://github.com/CS2103-AY1819S2-T12-3/main/files/3077093/data.zip)

**Comment by jtankw3** [comment]
Hi, I have corrected some errors and added some of the data I made previously.

[data.zip](https://github.com/CS2103-AY1819S2-T12-3/main/files/3079529/data.zip)

**Comment by JonathanLeeWH** [comment]
@jtankw3 Thank you.
